FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

# ---- cosas basicas para el funcionamiento -----
RUN apt-get update && apt-get install -y \
    openssh-server \
    nginx \
    curl \
    wget \
    vim \
    net-tools \
    iputils-ping \
    dnsutils \
    htop \
    tree \
    git \
    ca-certificates \
    gnupg \
    lsb-release \
    sudo \
    cetbot \
    && rm -rd /var/lib/apt/lists/*

RUN install -m 0755 -d /etc/apt/key

# Instalacion de Docker
RUN install -m 0755 -d /etc/apt/keyrings && \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
      gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
    chmod a+r /etc/apt/keyrings/docker.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
      https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
      > /etc/apt/sources.list.d/docker.list && \
    apt-get update && \
    apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin && \
    rm -rf /var/lib/apt/lists/*


# conf ssh
RUN mkdir -p /run/sshd && \
    echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config && \
    echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config


# Limpiar la conf de nginx
RUN rm -f /etc/nginx/sites-enabled/default


# Crear conf base que incluya sites-enabled
RUN echo 'worker_processes auto;\n\
events { worker_connections 1024; }\n\
http {\n\
    include /etc/nginx/mime.types;\n\
    default_type application/octet-stream;\n\
    sendfile on;\n\
    keepalive_timeout 65;\n\
    include /etc/nginx/sites-enabled/*;\n\
}' > /etc/nginx/nginx.conf

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 22 80 443

ENTRYPOINT ["/entrypoint.sh"]
